import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "developers/api/api",
    },
    {
      type: "category",
      label: "users",
      items: [
        {
          type: "doc",
          id: "developers/api/get-bulk-users",
          label: "Get Bulk Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-i-ds-by-addresses",
          label: "Get User IDs by Addresses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-by-handle",
          label: "Get User by Handle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-ai-attributed-tracks-by-user-handle",
          label: "Get AI Attributed Tracks by User Handle",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/search-users",
          label: "Search Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/verify-id-token",
          label: "Verify ID Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user",
          label: "Get User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-albums-by-user",
          label: "Get Albums by User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-authorized-apps",
          label: "Get Authorized Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-balance-history",
          label: "Get User Balance History",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-challenges",
          label: "Get User Challenges",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-coins",
          label: "Get User Coins",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-coin",
          label: "Get User Coin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-collectibles",
          label: "Get User Collectibles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-comments",
          label: "Get User Comments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-connected-wallets",
          label: "Get connected wallets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-developer-apps",
          label: "Get Developer Apps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-favorites",
          label: "Get Favorites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-followers",
          label: "Get Followers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-following",
          label: "Get Following",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-users-track-history",
          label: "Get User's Track History",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-monthly-track-listens",
          label: "Get User Monthly Track Listens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-muted-users",
          label: "Get Muted Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-mutual-followers",
          label: "Get Mutual Followers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-playlists-by-user",
          label: "Get Playlists by User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-purchasers",
          label: "Get purchasers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/download-purchases-as-csv",
          label: "Download Purchases as CSV",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-recommended-tracks",
          label: "Get User Recommended Tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-related-users",
          label: "Get Related Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-remixers",
          label: "Get remixers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-reposts",
          label: "Get Reposts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-sales-aggregate",
          label: "Get Sales Aggregate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/download-sales-as-csv",
          label: "Download Sales as CSV",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/download-sales-as-json",
          label: "Download Sales as JSON",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-subscribers",
          label: "Get Subscribers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-supporters",
          label: "Get Supporters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-supported-users",
          label: "Get Supported Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-top-track-tags",
          label: "Fetch most used tags in a user's tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-tracks-by-user",
          label: "Get Tracks by User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-tracks-remixed",
          label: "Get User Tracks Remixed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/download-usdc-withdrawals-as-csv",
          label: "Download USDC Withdrawals as CSV",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-user-email-key",
          label: "Get User Email Key",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "playlists",
      items: [
        {
          type: "doc",
          id: "developers/api/get-bulk-playlists",
          label: "Get Bulk Playlists",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-playlist-by-handle-and-slug",
          label: "Get Playlist By Handle and Slug",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/search-playlists",
          label: "Search Playlists",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-trending-playlists",
          label: "Get Trending Playlists",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-playlist",
          label: "Get Playlist",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-playlist-access-info",
          label: "Get Playlist Access Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-playlist-tracks",
          label: "Get Playlist Tracks",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "tracks",
      items: [
        {
          type: "doc",
          id: "developers/api/get-bulk-tracks",
          label: "Get Bulk Tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/inspect-tracks",
          label: "Inspects the details of the files for multiple tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-recent-premium-tracks",
          label: "Get Recent Premium Tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-feeling-lucky-tracks",
          label: "Get Feeling Lucky Tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-tracks-with-recent-comments",
          label: "Get Tracks With Recent Comments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-most-shared-tracks",
          label: "Get Most Shared Tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/search-tracks",
          label: "Search Tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-trending-tracks",
          label: "Get Trending Tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-underground-trending-tracks",
          label: "Get Underground Trending Tracks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-track",
          label: "Get Track",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-track-access-info",
          label: "Get Track Access Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-track-comment-count",
          label: "Get Track Comment Count",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-track-comment-notification-setting",
          label: "Get Track Comment Notification Setting",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-track-comments",
          label: "Get Track Comments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/download-track",
          label: "Download the original or MP3 file of a track",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/inspect-track",
          label: "Inspects the details of the file for a track",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-track-stems",
          label: "Get Track Stems",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/stream-track",
          label: "Get the streamable MP3 file of a track",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-track-top-listeners",
          label: "Get Track Top Listeners",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "challenges",
      items: [
        {
          type: "doc",
          id: "developers/api/get-undisbursed-challenges",
          label: "Get Undisbursed Challenges",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-undisbursed-challenges-for-user",
          label: "Get Undisbursed Challenges For User",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "tips",
      items: [
        {
          type: "doc",
          id: "developers/api/get-tips",
          label: "Get Tips",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "developer_apps",
      items: [
        {
          type: "doc",
          id: "developers/api/get-developer-app",
          label: "Get Developer App",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "dashboard_wallet_users",
      items: [
        {
          type: "doc",
          id: "developers/api/bulk-get-dashboard-wallet-users",
          label: "Bulk get dashboard wallet users",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "resolve",
      items: [
        {
          type: "doc",
          id: "developers/api/resolve",
          label: "Resolves and redirects a provided Audius app URL to the API resource URL it represents",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "comments",
      items: [
        {
          type: "doc",
          id: "developers/api/get-unclaimed-comment-id",
          label: "Get unclaimed comment ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-comment",
          label: "Get Comment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-comment-replies",
          label: "Get Comment Replies",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "events",
      items: [
        {
          type: "doc",
          id: "developers/api/get-bulk-events",
          label: "Get Bulk Events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-all-events",
          label: "Get all events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-entity-events",
          label: "Get events for a specific entity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-unclaimed-event-id",
          label: "Get unclaimed event ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "explore",
      items: [
        {
          type: "doc",
          id: "developers/api/get-best-selling",
          label: "Get best selling tracks and/or albums",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "rewards",
      items: [
        {
          type: "doc",
          id: "developers/api/claim-rewards",
          label: "Claim Rewards",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "developers/api/create-reward-code",
          label: "Create Reward Code",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "wallet",
      items: [
        {
          type: "doc",
          id: "developers/api/get-wallet-coins",
          label: "Get Wallet Coins",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "coins",
      items: [
        {
          type: "doc",
          id: "developers/api/get-coins",
          label: "Get Coins",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/create-coin",
          label: "Create Coin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "developers/api/get-coin",
          label: "Get Coin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/update-coin",
          label: "Update Coin",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "developers/api/get-coin-by-ticker",
          label: "Get Coin By Ticker",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-coin-insights",
          label: "Get Coin Insights",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-coin-members",
          label: "Get Coin Members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-coin-members-count",
          label: "Get Coin Members Count",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-volume-leaders",
          label: "Get Volume Leaders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/get-coin-redeem-amount",
          label: "Get Coin Redeem Amount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/claim-coin-reward",
          label: "Claim Coin Reward",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "developers/api/get-reward-code",
          label: "Get Reward Code",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "developers/api/claim-coin-reward-code",
          label: "Claim Coin Reward Code",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
